#!/usr/local/bin/python
# -*- coding: utf-8 -*-
import os
import re
import sys
from cli.cli import safe_entry_point
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(safe_entry_point())

